### ISSUE TITLE
WireGuard kernel module does not compile on 5.1.x

### ISSUE THREAD

**Issue by rn** [linuxkit/linuxkit#3346]
@zx2c4 in case you don't know, but the WireGuard kernel module does not compile against 5.1.x kernels:

```
    AS [M]  /wireguard/crypto/zinc/chacha20/chacha20-x86_64.o
    In file included from <command-line>:
    /wireguard/compat/compat.h:795:10: fatal error: net/netfilter/nf_nat_core.h: No such file or directory
     #include <net/netfilter/nf_nat_core.h>
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by zx2c4** [comment]
This was fixed a while ago in upstream wireguard, but you with nobody maintaining your wireguard package, I guess you didn't get the fix.
