### PR TITLE
Bump to containerd v1.0.0-beta.2

### PR DESCRIPTION
**Pull request by ijc**
Bumps containerd to v1.0.0-beta.2 in the usual semi-mechanical way

Also bumps runc to 0351df1c5a66838d0c392b4ac4cf9450de844e2d which is the one used by this containerd release /cc @SvenDowideit this replaces #2569.

### CODE REVIEW

**Comment by ijc** [comment]
A smoke test on arm64 using the linuxkit.yml` (with `nginx:alpine` removed for not existing) worked.

@justincormack the issue we discussed IRL was my `bin/moby` being super old.

**Comment by justincormack** [comment]
the `containerd` test failed in CI...

**Comment by ijc** [comment]
Yep, investigating.

**Comment by ijc** [comment]
```
[STDERR  ] 2017-10-12T13:00:00.869932647Z: # github.com/containerd/containerd/metadata
[STDERR  ] 2017-10-12T13:00:00.869942372Z: metadata/db_test.go:322: undefined: pprof.Labels
[STDERR  ] 2017-10-12T13:00:00.86994773Z: metadata/db_test.go:323: undefined: pprof.Do
[STDERR  ] 2017-10-12T13:00:00.869956803Z: metadata/images_test.go:476: t.Helper undefined (type *testing.T has no field or method Helper)
[STDERR  ] 2017-10-12T13:00:00.869962143Z: metadata/images_test.go:499: t.Helper undefined (type *testing.T has no field or method Helper)
[STDERR ] 2017-10-12T13:00:00.869967592Z: FAIL github.com/containerd/containerd/metadata [build failed]
```
Seems to be an upstream build error. I'll gather some details into an upstream issue and add a skip to this test with that as a reference.

**Comment by ijc** [comment]
Having now looked at the code I think this is a go 1.8 vs 1.9 issue. I'll investigate updating our 1.8 once I've confirmed the diagnosis.

**Comment by ijc** [comment]
Looks like https://github.com/containerd/containerd/issues/1215 needed a bump to 1.9 to fix, so CI switched to 1.9 which allowed the use of some 1.9 only methods to get into a test.

**Comment by ijc** [comment]
Merging now as is, I will work on a follow up PR to bump go 1.9.
